[package]
name = "touchpointdb"
version = "0.1.0"
authors = ["Rocky Signavong <rsignavong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = "0.3.1"
memmap = "0.7.0"
rayon = "1.1.0"
twoway = "0.2.0"
