processor_id = "123"
rust_log="importations"
status_heartbeat_interval = "123"

[aws]
access_key = ""
secret_access_key = ""

[kafka.config]
brokers = [ "localhost:9092" ]
# debug = "all"
group_id = "importations"
timeout = 5000

[kafka.consumers.import_instances]
# debug = "all"
topics = [""]

[kafka.producers.status]
# debug = "all"
topic = ""
