processor_id = "123"
rust_log="reconciliations"
status_heartbeat_interval = 1_000

[kafka.config]
brokers = [ "localhost:9092" ]
# debug = "msg,topic"
group_id = "reconciliations-dev"
timeout = 30_000

[kafka.consumers.reconciliation_data]
# debug = "msg,topic"
topics = ["calions-int-evt-reconciliation_data"]

[kafka.consumers.reconciliation_process]
# debug = "msg,topic"
topics = ["calions-int-evt-reconciliation_process"]

[kafka.producers.reconciliation_data]
# debug = "all"
topic = ""

[kafka.producers.status]
# debug = "msg,topic"
topic = "calions-int-evt-reconciliation_status"
